#!/usr/bin/env python3
"""
Adopt AI-readiness patterns into an existing repository.

Detects the project's stack, generates a verification scaffold
(Makefile, AGENTS.md, ADR template, SECURITY.md, CI workflow stub,
drill stubs), and reports what was created.

⚠ WARNING: This tool generates scaffold files from templates.
The output is a STARTING POINT that requires human review.
- Generated linter configs may not match your project's conventions.
- Generated CI workflows need secrets and runner configuration.
- Generated AGENTS.md needs project-specific constraints added.
- Generated drills are stubs — they prove the pattern, not your rules.

Do not merge generated files without reviewing them first.
Run the generated `make verify` and fix any failures before trusting it.

Usage:
    python scripts/adopt.py /path/to/repo              # generate scaffold
    python scripts/adopt.py /path/to/repo --dry-run    # show what would happen
    python scripts/adopt.py /path/to/repo --detect     # detect stack only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if sys.version_info < (3, 9):
    sys.exit("adopt.py requires Python 3.9 or newer (found %s)" % sys.version.split()[0])

# ponytail: detection by file presence, fine for common stacks;
# replace with a plugin registry if this grows beyond 10 stacks

WARNING = """
# ⚠ GENERATED FILE — REVIEW BEFORE MERGING
#
# This file was generated by ai-ready-repo/scripts/adopt.py.
# It is a starting point, not a trusted output. AI agents are not
# deterministic — the same tool may produce different scaffolds on
# different runs. Review every line before committing.
#
# Source: https://github.com/vidanov/ai-ready-repo
"""

STACKS: dict[str, dict[str, str | None | list[str]]] = {
    "python": {
        "detect": "pyproject.toml,setup.py,setup.cfg,requirements.txt",
        "linter": "ruff check src tests",
        "formatter": "ruff format --check src tests",
        "typecheck": "mypy src",
        "test": "pytest tests/ -v --cov=src",
        "boundaries": "lint-imports",
        "bootstrap": "uv venv && uv pip install -e '.[dev]'",
        "lockfile": "uv.lock,poetry.lock,requirements.txt",
    },
    "node-typescript": {
        "detect": "package.json,tsconfig.json",
        "linter": "npx eslint src/",
        "formatter": "npx prettier --check src/",
        "typecheck": "npx tsc --noEmit",
        "test": "npx jest --coverage",
        "boundaries": "npx eslint --rule 'import/no-restricted-paths: error'",
        "bootstrap": "npm ci",
        "lockfile": "package-lock.json,yarn.lock,pnpm-lock.yaml",
    },
    "terraform": {
        "detect": "**/*.tf,.terraform-version,terraform.tfvars",
        "linter": "tflint --recursive",
        "formatter": "terraform fmt -check -recursive",
        "typecheck": None,
        "test": "terraform validate",
        "boundaries": "checkov -d . --quiet",
        "bootstrap": "terraform init",
        "lockfile": ".terraform.lock.hcl",
    },
    "cdk-typescript": {
        "detect": "cdk.json,tsconfig.json",
        "linter": "npx eslint lib/",
        "formatter": "npx prettier --check lib/",
        "typecheck": "npx tsc --noEmit",
        "test": "npx jest --coverage",
        "boundaries": "npx cdk-nag",
        "bootstrap": "npm ci && npx cdk synth",
        "lockfile": "package-lock.json",
    },
    "go": {
        "detect": "go.mod,go.sum",
        "linter": "golangci-lint run ./...",
        "formatter": "gofmt -l .",
        "typecheck": "go vet ./...",
        "test": "go test -race -coverprofile=coverage.out ./...",
        "boundaries": None,
        "bootstrap": "go mod download",
        "lockfile": "go.sum",
    },
    "rust": {
        "detect": "Cargo.toml,Cargo.lock",
        "linter": "cargo clippy -- -D warnings",
        "formatter": "cargo fmt --check",
        "typecheck": None,
        "test": "cargo test",
        "boundaries": None,
        "bootstrap": "cargo build",
        "lockfile": "Cargo.lock",
    },
    "java-maven": {
        "detect": "pom.xml",
        "linter": "mvn checkstyle:check",
        "formatter": None,
        "typecheck": "mvn compile",
        "test": "mvn test",
        "boundaries": None,
        "bootstrap": "mvn install -DskipTests",
        "lockfile": None,
    },
}


def detect_stack(repo: Path) -> list[str]:
    """Detect which stacks are present in the repo."""
    found = []
    for name, config in STACKS.items():
        detect_files = str(config["detect"]).split(",")
        for pattern in detect_files:
            if pattern.startswith("*"):
                if list(repo.glob(pattern)):
                    found.append(name)
                    break
            elif (repo / pattern).exists():
                found.append(name)
                break
    return found


def generate_makefile(stack_name: str, config: dict) -> str:
    """Generate a Makefile for the detected stack."""
    lines = [WARNING.replace("# ", "## "), ""]
    lines.append(".DEFAULT_GOAL := help\n")

    if config.get("bootstrap"):
        lines.append(f".PHONY: bootstrap")
        lines.append(f"bootstrap: ## Set up development environment")
        lines.append(f"\t{config['bootstrap']}\n")

    if config.get("formatter"):
        lines.append(f".PHONY: format-check")
        lines.append(f"format-check: ## Check formatting")
        lines.append(f"\t{config['formatter']}\n")

    if config.get("linter"):
        lines.append(f".PHONY: lint")
        lines.append(f"lint: ## Run linter")
        lines.append(f"\t{config['linter']}\n")

    if config.get("typecheck"):
        lines.append(f".PHONY: typecheck")
        lines.append(f"typecheck: ## Run type checker")
        lines.append(f"\t{config['typecheck']}\n")

    if config.get("boundaries"):
        lines.append(f".PHONY: boundary-check")
        lines.append(f"boundary-check: ## Enforce module boundaries")
        lines.append(f"\t{config['boundaries']}\n")

    if config.get("test"):
        lines.append(f".PHONY: test")
        lines.append(f"test: ## Run tests")
        lines.append(f"\t{config['test']}\n")

    # Build verify target from available checks
    checks = []
    if config.get("formatter"):
        checks.append("format-check")
    if config.get("linter"):
        checks.append("lint")
    if config.get("typecheck"):
        checks.append("typecheck")
    if config.get("boundaries"):
        checks.append("boundary-check")
    if config.get("test"):
        checks.append("test")

    lines.append(f".PHONY: verify")
    lines.append(f"verify: {' '.join(checks)} ## Run all checks")
    lines.append(f'\t@echo "✓ All checks passed"\n')

    lines.append(".PHONY: help")
    lines.append("help: ## Show this help")
    lines.append('\t@grep -E \'^[a-zA-Z_-]+:.*?## .*$$\' $(MAKEFILE_LIST) \\')
    lines.append('\t\t| awk \'BEGIN {FS = ":.*?## "}; {printf "  \\033[36m%-20s\\033[0m %s\\n", $$1, $$2}\'')

    return "\n".join(lines) + "\n"


def generate_agents_md(stack_name: str, config: dict) -> str:
    """Generate AGENTS.md for the detected stack."""
    sections = [WARNING, ""]
    sections.append("# AGENTS.md\n")
    sections.append(f"Stack: {stack_name}\n")
    sections.append("## Commands\n")
    sections.append("```bash")
    if config.get("bootstrap"):
        sections.append(f"make bootstrap   # set up from fresh clone")
    sections.append(f"make verify      # run all checks (same as CI)")
    sections.append("```\n")
    sections.append("## Non-obvious constraints\n")
    sections.append("<!-- TODO: Add project-specific constraints here. -->")
    sections.append("<!-- Examples: -->")
    sections.append("<!-- - Import boundaries: domain must not import infrastructure -->")
    sections.append("<!-- - Coverage minimum: 80% -->")
    sections.append("<!-- - Protected paths: docs/adr/ requires architecture review -->\n")
    sections.append("## Completion evidence\n")
    sections.append("A task is done when `make verify` passes. Not before.\n")
    return "\n".join(sections)


def generate_adr_template() -> str:
    """Generate an ADR template."""
    return WARNING + """
---
id: ADR-XXX-001
status: proposed
scope:
  - path/to/governed/files/**
---

# Decision title

## Decision

What was decided and how it is enforced.

## Reasons

Why this constraint exists. What breaks without it.

## Verification

```bash
# Command that proves the constraint holds
make verify
```

## Firing condition

How to prove the gate can convict (a drill that plants a violation
and asserts the check catches it). A gate that has never fired is
indistinguishable from a gate that cannot fire.

## Retirement

When to remove this constraint. What conditions would make it
obsolete or harmful.
"""


def generate_security_md() -> str:
    """Generate SECURITY.md stub."""
    return WARNING + """
# Security Policy

## Agent token scope

When granting an AI coding agent access to this repository, use a
fine-grained token with minimum permissions. See the ai-ready-repo
template for recommended and withheld permissions:
https://github.com/vidanov/ai-ready-repo/blob/main/SECURITY.md

## Reporting a vulnerability

<!-- TODO: Replace with your security contact -->
Email: security@example.com
"""


def adopt(repo: Path, dry_run: bool = False) -> int:
    """Generate AI-readiness scaffold for the given repo."""
    stacks = detect_stack(repo)

    if not stacks:
        print("No recognized stack detected.", file=sys.stderr)
        print("Looked for:", ", ".join(STACKS.keys()), file=sys.stderr)
        return 1

    primary = stacks[0]
    config = STACKS[primary]

    print(f"Detected stack: {primary}")
    if len(stacks) > 1:
        print(f"Also found: {', '.join(stacks[1:])}")
    print()

    print("⚠ WARNING: Generated files are a STARTING POINT.")
    print("  Review every file before committing.")
    print("  AI agents are not deterministic.")
    print()

    files: dict[str, str] = {}

    # Only generate files that don't already exist
    if not (repo / "Makefile").exists():
        files["Makefile"] = generate_makefile(primary, config)

    if not (repo / "AGENTS.md").exists():
        files["AGENTS.md"] = generate_agents_md(primary, config)

    if not (repo / "SECURITY.md").exists():
        files["SECURITY.md"] = generate_security_md()

    adr_dir = repo / "docs" / "adr"
    if not adr_dir.exists():
        files["docs/adr/ADR-TEMPLATE.md"] = generate_adr_template()

    if not files:
        print("All scaffold files already exist. Nothing to generate.")
        print("Run scripts/ai_readiness_audit.py to check what's missing.")
        return 0

    for path, content in sorted(files.items()):
        full_path = repo / path
        if dry_run:
            print(f"  would create  {path}")
        else:
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            print(f"  created  {path}")

    print()
    print(f"Generated {len(files)} file(s) for {primary}.")
    print()
    print("Next steps:")
    print("  1. Review every generated file — they are templates, not truths.")
    print("  2. Run `make verify` and fix any failures.")
    print("  3. Add project-specific constraints to AGENTS.md.")
    print("  4. Create your first ADR from docs/adr/ADR-TEMPLATE.md.")
    print("  5. Delete ADR-TEMPLATE.md after creating a real ADR.")
    print()
    print("Audit your progress:")
    print(f"  python scripts/ai_readiness_audit.py {repo}")

    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Adopt AI-readiness patterns into an existing repository"
    )
    parser.add_argument("repo", type=Path, help="Path to the target repository")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be created")
    parser.add_argument("--detect", action="store_true", help="Detect stack only")
    args = parser.parse_args()

    if not args.repo.is_dir():
        print(f"Not a directory: {args.repo}", file=sys.stderr)
        return 1

    if args.detect:
        stacks = detect_stack(args.repo)
        if stacks:
            print(f"Detected: {', '.join(stacks)}")
        else:
            print("No recognized stack detected.")
        return 0

    return adopt(args.repo, dry_run=args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
