#!/usr/bin/env bash
# setup_tool_bridges.sh — wire AGENTS.md into every coding agent's expected config.
#
# AGENTS.md is the single source of truth. This script creates bridge files
# so tools that read CLAUDE.md, .cursorrules, .github/copilot-instructions.md,
# or .aider.conf.yml all find their way back to the same instructions.
#
# Usage:
#   bash scripts/setup_tool_bridges.sh              # create pointer files
#   bash scripts/setup_tool_bridges.sh --dry-run    # show what would happen
#   bash scripts/setup_tool_bridges.sh --force      # overwrite existing bridges
#   bash scripts/setup_tool_bridges.sh --clean      # remove all bridge files
#
# Idempotent. Existing files are left alone unless --force.

set -euo pipefail

DRY=0
FORCE=0
CLEAN=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --force)   FORCE=1 ;;
    --clean)   CLEAN=1 ;;
    -h|--help)
      sed -n '2,/^$/s/^# //p' "$0"
      exit 0
      ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

say() { printf '%s\n' "$*"; }

[ -f AGENTS.md ] || {
  echo "ERROR: no AGENTS.md in $(pwd)." >&2
  exit 1
}

# All bridge files this script manages
BRIDGES=(
  "CLAUDE.md"
  ".cursorrules"
  ".cursor/rules/python-source.mdc"
  ".cursor/rules/tests.mdc"
  ".cursor/rules/cdk-typescript.mdc"
  ".cursor/rules/terraform.mdc"
  ".cursor/rules/docs.mdc"
  ".github/copilot-instructions.md"
  ".aider.conf.yml"
  ".gemini/settings.json"
  ".windsurfrules"
  ".kiro/steering/RULES.md"
)

if [ "$CLEAN" = 1 ]; then
  say "Cleaning bridge files..."
  for f in "${BRIDGES[@]}"; do
    if [ -f "$f" ]; then
      if [ "$DRY" = 1 ]; then
        say "  would remove  $f"
      else
        rm "$f"
        say "  removed  $f"
      fi
    fi
  done
  say "Done."
  exit 0
fi

say "AGENTS.md found in $(pwd)"
[ "$DRY" = 1 ] && say "(dry run)"
say ""

write_file() {
  local path="$1" content="$2"
  if [ -e "$path" ] && [ "$FORCE" != 1 ]; then
    say "  skip    $path (exists, use --force to overwrite)"
    return
  fi
  if [ "$DRY" = 1 ]; then
    say "  create  $path"
    return
  fi
  mkdir -p "$(dirname "$path")"
  if [ -e "$path" ]; then
    cp -p "$path" "$path.bak"
    say "  overwrite  $path (backup at $path.bak)"
  else
    say "  create  $path"
  fi
  printf '%s\n' "$content" > "$path"
}

# --- Claude Code ---
# Claude Code reads CLAUDE.md at project root. @import pulls in AGENTS.md.
write_file "CLAUDE.md" "@AGENTS.md

# Claude Code bridge — generated by scripts/setup_tool_bridges.sh
# Add Claude-specific instructions below this line, if any.
# The verification command is: make verify"

# --- Cursor ---
# Cursor reads .cursorrules at project root.
write_file ".cursorrules" "# Cursor rules — generated by scripts/setup_tool_bridges.sh
# Source of truth: AGENTS.md
#
# Read AGENTS.md for project structure, conventions, and constraints.
# The verification command is: make verify
# Run it before claiming any task is complete.
#
# Import boundaries are enforced by CI (import-linter).
# ADRs in docs/adr/ have Verification and Retirement sections.
# Every rule has a firing condition — a way to prove the gate works.
#
# For ecosystem-specific rules, see:
#   ecosystems/cdk-typescript/AGENTS.md
#   ecosystems/terraform/AGENTS.md"

# --- GitHub Copilot ---
# Copilot reads .github/copilot-instructions.md
write_file ".github/copilot-instructions.md" "# Copilot instructions — generated by scripts/setup_tool_bridges.sh

Follow the repository's \`AGENTS.md\` at the project root. It is the single
source of truth for build commands, project structure, and conventions.

Key commands:
- \`make bootstrap\` — set up from fresh clone
- \`make verify\` — run all checks (same as CI)
- \`make drill-transition-guard\` — prove the domain guard works
- \`make drill-import-check\` — prove the import boundary works

Import boundaries (domain/application/infrastructure) are enforced by CI.
Do not add cross-layer imports without updating \`pyproject.toml\` contracts."

# --- Aider ---
# Aider reads .aider.conf.yml
write_file ".aider.conf.yml" "# Aider config — generated by scripts/setup_tool_bridges.sh
read: AGENTS.md"

# --- Gemini CLI ---
# Gemini reads .gemini/settings.json
write_file ".gemini/settings.json" '{
  "context": { "fileName": "AGENTS.md" }
}'

# --- Windsurf ---
# Windsurf reads .windsurfrules at project root.
write_file ".windsurfrules" "# Windsurf rules — generated by scripts/setup_tool_bridges.sh
# Source of truth: AGENTS.md
#
# Read AGENTS.md for project structure, conventions, and constraints.
# The verification command is: make verify
# Run it before claiming any task is complete."

# --- Kiro CLI ---
# Kiro reads .kiro/steering/*.md as persistent rules across sessions.
write_file ".kiro/steering/RULES.md" "# ai-ready-repo — agent steering rules
# Generated by scripts/setup_tool_bridges.sh
# Source of truth: AGENTS.md

## How to work with this repo

This is a verification-first repository. Every rule that can be enforced
by a tool is enforced by a tool. AGENTS.md documents only what tools
cannot check.

**Before making changes:**
1. Read \`AGENTS.md\` for the full constraint surface.
2. Run \`make verify\` to see what green looks like before you touch anything.
3. Check \`docs/adr/\` for architecture decisions that explain why things
   are the way they are. Each ADR has a Retirement section — if the
   constraint looks wrong, the ADR tells you when to remove it.

**While making changes:**
- Run \`make verify-fast\` for quick feedback (format + lint + typecheck).
- Import boundaries are enforced by CI. If \`make import-check\` fails,
  the import direction is wrong (domain cannot import infrastructure).
- Do not weaken tests to make them pass. Do not disable linter rules.
  \`make verify-tamperproof\` will catch it.

**Before claiming done:**
- Run \`make verify\` (the full ladder).
- If you added a new rule, add a firing condition (drill) that proves
  the rule can convict. A gate that has never fired is indistinguishable
  from a gate that cannot fire.

## Verification
\`make verify\` runs: format-check → lint → typecheck → import-check →
test-unit → validate-adrs. All must pass.

## Import boundaries (CI-enforced)
Three layers: domain → application → infrastructure. One-way only.
- \`domain/\` must NOT import from \`application/\` or \`infrastructure/\`.
- \`application/\` may import \`domain/\`.
- \`infrastructure/\` may import \`domain/\` and \`application/\`.

## Drills (prove gates work)
- \`make drill-transition-guard\` — domain guard fires on invalid transition
- \`make drill-import-check\` — import boundary rejects forbidden import
- \`make drill-import-permit\` — import boundary permits legal import
- \`make drill-deny-catalog\` — deny rules golden-file locked and firing
- \`make drill-dead-config\` — no dead config keys in pyproject.toml
- \`make drill-ci-coverage\` — every verification target runs in CI

## Non-obvious constraints
- Tests require 80% coverage (\`pyproject.toml\` fail_under).
- \`CODEOWNERS\` routes sensitive paths to named teams.
- The deny catalog (\`scripts/deny_catalog_golden.json\`) is additive-only.
  You can add deny patterns. You cannot remove baseline ones.
- ADRs must have Verification and Retirement sections.

## When you are stuck
- If the task looks impossible, say so and stop. Do not escalate to
  creative workarounds outside the task scope.
- If a test fails and you do not understand why, read the ADR linked
  in the test comment before changing the test.
- If you are unsure whether an import is allowed, run \`make import-check\`
  rather than guessing. The linter is the authority, not the instruction."

# --- Cursor scoped rules ---
# Cursor reads .cursor/rules/*.mdc for path-scoped instructions.
write_file ".cursor/rules/python-source.mdc" "---
description: Rules for editing Python domain, application, and infrastructure code
globs: src/**/*.py
alwaysApply: false
---
# Python source code
## Import boundaries (CI-enforced)
Three layers: domain → application → infrastructure. Direction is one-way.
domain/ must NOT import from application/ or infrastructure/.
Violations fail CI via import-linter. Check locally: make import-check
Run make verify before claiming any task is complete."

write_file ".cursor/rules/tests.mdc" "---
description: Rules for editing test files
globs: tests/**/*.py
alwaysApply: false
---
# Test files
Unit tests must maintain 100% coverage. Run: make test-unit
Do not weaken test assertions to make them pass.
Run make verify-tamperproof to check from a trusted copy."

write_file ".cursor/rules/cdk-typescript.mdc" "---
description: Rules for CDK TypeScript ecosystem
globs: ecosystems/cdk-typescript/**
alwaysApply: false
---
# CDK TypeScript
Read ecosystems/cdk-typescript/AGENTS.md for full constraints.
cdk-nag is mandatory on every stack (ADR-CDK-001).
Run: cd ecosystems/cdk-typescript && make verify"

write_file ".cursor/rules/terraform.mdc" "---
description: Rules for Terraform ecosystem
globs: ecosystems/terraform/**
alwaysApply: false
---
# Terraform
Read ecosystems/terraform/AGENTS.md for full constraints.
All resources MUST be inside modules/, not at root level (ADR-TF-001).
Run: cd ecosystems/terraform && make verify"

write_file ".cursor/rules/docs.mdc" "---
description: Rules for documentation and ADRs
globs: docs/**/*.md
alwaysApply: false
---
# Documentation and ADRs
Every ADR must have: id, status, scope in frontmatter.
Must have ## Verification and ## Retirement sections.
Validate: make validate-adrs"

say ""
say "Native AGENTS.md support (no bridge needed):"
say "  Codex, Amp, opencode, Jules, Devin, goose, Warp, RooCode, Kilo Code, Zed"
say ""
say "Bridge files created. Verify with:"
say "  ls -la CLAUDE.md .cursorrules .windsurfrules .aider.conf.yml .gemini/settings.json .github/copilot-instructions.md .kiro/steering/RULES.md"
say ""
say "To remove all bridges: bash scripts/setup_tool_bridges.sh --clean"
