#!/usr/bin/env bash
# setup_tool_bridges.sh — wire AGENTS.md into every coding agent's expected config.
#
# AGENTS.md is the single source of truth. This script creates bridge files
# so tools that read CLAUDE.md, .cursorrules, .github/copilot-instructions.md,
# or .aider.conf.yml all find their way back to the same instructions.
#
# Usage:
#   bash scripts/setup_tool_bridges.sh              # create pointer files
#   bash scripts/setup_tool_bridges.sh --dry-run    # show what would happen
#   bash scripts/setup_tool_bridges.sh --force      # overwrite existing bridges
#   bash scripts/setup_tool_bridges.sh --clean      # remove all bridge files
#
# Idempotent. Existing files are left alone unless --force.

set -euo pipefail

DRY=0
FORCE=0
CLEAN=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --force)   FORCE=1 ;;
    --clean)   CLEAN=1 ;;
    -h|--help)
      sed -n '2,/^$/s/^# //p' "$0"
      exit 0
      ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

say() { printf '%s\n' "$*"; }

[ -f AGENTS.md ] || {
  echo "ERROR: no AGENTS.md in $(pwd)." >&2
  exit 1
}

# All bridge files this script manages
BRIDGES=(
  "CLAUDE.md"
  ".cursorrules"
  ".github/copilot-instructions.md"
  ".aider.conf.yml"
  ".gemini/settings.json"
  ".windsurfrules"
)

if [ "$CLEAN" = 1 ]; then
  say "Cleaning bridge files..."
  for f in "${BRIDGES[@]}"; do
    if [ -f "$f" ]; then
      if [ "$DRY" = 1 ]; then
        say "  would remove  $f"
      else
        rm "$f"
        say "  removed  $f"
      fi
    fi
  done
  say "Done."
  exit 0
fi

say "AGENTS.md found in $(pwd)"
[ "$DRY" = 1 ] && say "(dry run)"
say ""

write_file() {
  local path="$1" content="$2"
  if [ -e "$path" ] && [ "$FORCE" != 1 ]; then
    say "  skip    $path (exists, use --force to overwrite)"
    return
  fi
  if [ "$DRY" = 1 ]; then
    say "  create  $path"
    return
  fi
  mkdir -p "$(dirname "$path")"
  if [ -e "$path" ]; then
    cp -p "$path" "$path.bak"
    say "  overwrite  $path (backup at $path.bak)"
  else
    say "  create  $path"
  fi
  printf '%s\n' "$content" > "$path"
}

# --- Claude Code ---
# Claude Code reads CLAUDE.md at project root. @import pulls in AGENTS.md.
write_file "CLAUDE.md" "@AGENTS.md

# Claude Code bridge — generated by scripts/setup_tool_bridges.sh
# Add Claude-specific instructions below this line, if any.
# The verification command is: make verify"

# --- Cursor ---
# Cursor reads .cursorrules at project root.
write_file ".cursorrules" "# Cursor rules — generated by scripts/setup_tool_bridges.sh
# Source of truth: AGENTS.md
#
# Read AGENTS.md for project structure, conventions, and constraints.
# The verification command is: make verify
# Run it before claiming any task is complete.
#
# Import boundaries are enforced by CI (import-linter).
# ADRs in docs/adr/ have Verification and Retirement sections.
# Every rule has a firing condition — a way to prove the gate works.
#
# For ecosystem-specific rules, see:
#   ecosystems/cdk-typescript/AGENTS.md
#   ecosystems/terraform/AGENTS.md"

# --- GitHub Copilot ---
# Copilot reads .github/copilot-instructions.md
write_file ".github/copilot-instructions.md" "# Copilot instructions — generated by scripts/setup_tool_bridges.sh

Follow the repository's \`AGENTS.md\` at the project root. It is the single
source of truth for build commands, project structure, and conventions.

Key commands:
- \`make bootstrap\` — set up from fresh clone
- \`make verify\` — run all checks (same as CI)
- \`make drill-transition-guard\` — prove the domain guard works
- \`make drill-import-check\` — prove the import boundary works

Import boundaries (domain/application/infrastructure) are enforced by CI.
Do not add cross-layer imports without updating \`pyproject.toml\` contracts."

# --- Aider ---
# Aider reads .aider.conf.yml
write_file ".aider.conf.yml" "# Aider config — generated by scripts/setup_tool_bridges.sh
read: AGENTS.md"

# --- Gemini CLI ---
# Gemini reads .gemini/settings.json
write_file ".gemini/settings.json" '{
  "context": { "fileName": "AGENTS.md" }
}'

# --- Windsurf ---
# Windsurf reads .windsurfrules at project root.
write_file ".windsurfrules" "# Windsurf rules — generated by scripts/setup_tool_bridges.sh
# Source of truth: AGENTS.md
#
# Read AGENTS.md for project structure, conventions, and constraints.
# The verification command is: make verify
# Run it before claiming any task is complete."

say ""
say "Native AGENTS.md support (no bridge needed):"
say "  Codex, Kiro, Amp, opencode, Jules, Devin, goose, Warp, RooCode, Kilo Code, Zed"
say ""
say "Bridge files created. Verify with:"
say "  ls -la CLAUDE.md .cursorrules .windsurfrules .aider.conf.yml .gemini/settings.json .github/copilot-instructions.md"
say ""
say "To remove all bridges: bash scripts/setup_tool_bridges.sh --clean"
